local test = require("test")
local args = require("args")
local json = require("json")
local dialog = require("dialog")
local app = require("app")
local editor = require("editor")
local ui = require("ui")
local function define_tests()
    test.describe("Agent draft handoff", function()
        test.it("preserves old arguments and roundtrips a multiline Workshop request", function()
            local old = assert(args.parse("user_agent:one\nBuilder"))
            test.eq(old.agent, "user_agent:one"); test.eq(old.title, "Builder"); test.eq(old.draft, "")
            local draft = "Change this tool:\nreturn {main = function() end}\nKeep its name."
            local parsed = assert(args.parse(json.encode({agent_id = "user_agent:one", title = "Builder", draft = draft})))
            test.eq(parsed.agent, old.agent); test.eq(parsed.draft, draft)
            test.is_nil(args.parse('{"draft":"missing agent"}'))
            test.is_nil(args.parse('{"agent_id":"one","draft":42}'))
        end)
        test.it("shows and edits a multiline draft without sending it", function()
            local state = {messages = {}, draft = "First line\nSecond line", long_draft = true,
                pid = "not-a-real-session", busy = false, title = "Builder", status = "ready"}
            local context = app.context({width = 60, height = 24})
            local tree = dialog.definition.view(state, context)
            test.is_nil(ui.problem(tree))
            ui.plan(tree, 60, 24, context.interaction)
            test.eq(editor.text(context.editor("draft")), state.draft)
            editor.set(context.editor("draft"), "Changed\nRequest")
            dialog.definition.update(state, {type = "change", id = "draft"}, context)
            test.eq(state.draft, "Changed\nRequest")
            test.eq(#state.messages, 0); test.is_false(state.busy)
        end)
    end)
end
local run_cases = test.run_cases(define_tests)
return {run = function(options) return run_cases(options) end}
